# Site settings
title: Samuel Gratzl
email: contact@sgratzl.com
url: https://www.sgratzl.com
description: >
  Samuel Gratzl is a passionate Information visualizer and experienced Sofware Architect. 
  He loves to dig into code, hunt bugs, and design new platforms
skills: "Information Visualizer - Data Scientist - Software Architect"
meta_author: Gratzl Samuel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 006596 # 2c4e86 #80B3FF
  primary-rgb: "0,101,150" # "44,78,134" #"128,179,255"
  secondary: 2d3c4d #FD6E8A
  secondary-dark: 171f28 # 233140 #A2122F

# Footer settings
footer:
  copyright: Samuel Gratzl
  location: Location
  social: Around the Web
  credits: Credits

collections:
  - portfolio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: bitbucket
    url: https://bitbucket.org/sgratzl
  - title: github
    url: https://github.com/sgratzl

# Postal address (add as many lines as necessary)
address:
  - line: Griesmayrstrasse 23
  - line: 4040 Linz, Austria

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
